Repository ubsuny/CP1-24-HW2, pull requests merged in 2024-10, with the labels that each got.

#17 Added the .devcontainer directory (to setup the codespace for Python)
  .devcontainer/python/devcontainer.json
  Broadcasting.py
Labels: codespace

#22 Added axis summation script
  Array Axis Summation.ipynb
Labels: enhancement, Organization

#49 Array axis summations
  Array-axis-summations/Array Axis Summation.ipynb
  Array-axis-summations/ArrayAxisSummations.ipynb
Labels: documentation

#57 Diagonal return - Manual implementation added
  matrix_operations.py
  unit-tests.py
Labels: enhancement, python, testing

#53 Added a benchmark file for Matrix Multiplication and Dot Product
  Calculation Time for Matrix Multiplication.ipynb
  CalculationTimeForMatrixMultiplicationAndDotProduct.ipynb
  MatrixMultiplicationAndDotProductBenchmarks.md
Labels: documentation, Organization

#74 notebook_dir fix and example notebook added
  jupyter-notebooks/.ipynb_checkpoints/exampleNotebook-checkpoint.ipynb
  jupyter-notebooks/.ipynb_checkpoints/matrixDiagonal-checkpoint.ipynb
  jupyter-notebooks/exampleNotebook.ipynb
  jupyter-notebooks/example_notebook.ipynb
  jupyter-notebooks/matrixDiagonal.ipynb
Labels: documentation, Organization

#72 Updated matrix_operations.py with new imports and functions
  matrix_operations.py
Labels: enhancement

#70 Added Documentation for garbage Collection
  Handling Garbage Collection.md
Labels: documentation

#64 Vector Inner Product
  innerProduct.ipynb
  pVectorGenerator.py
Labels: architecture

#63 Moved jupyter-notebooks to respective folder
  MatrixMultiplicationAndDotProductBenchmarks.md
  jupyter-notebooks/ArrayAxisSummation.ipynb
  jupyter-notebooks/CalculationTimeForMatrixMultiplicationAndDotProduct.ipynb
Labels: Organization

#46 Python Code for Inner and Outer product
  InnerandOuterProduct.py
  documentation/InnerandOuterProduct.md
Labels: python

#59 Included for loop implementation of Matrix Dot Product in CalculationTimeMatrixMultiplicationAndDotProduct.ipynb Jupyter notebook
  CalculationTimeForMatrixMultiplicationAndDotProduct.ipynb
  MatrixMultiplicationAndDotProductBenchmarks.md
Labels: Organization, architecture

#77 Added the exception handling for Broadcasting
  BroadcastingInMultiplication.py
Labels: enhancement

#34 Added matrix trace computation methods and unit tests with detailed n…
  documentation/TraceOfArray.md
  test_trace.py
  trace_comparison.py
Labels: python, testing, codespace

#60 Update the markdown documentation for Matrix Multiplication and Dot Product
  CalculationTimeForMatrixMultiplicationAndDotProduct.ipynb
Labels: documentation, Organization

#79 Added the outerProduct file
  outerProduct.ipynb
Labels: architecture

#40 Added method to return the transpose of an array
  matrix_operations.py
Labels: enhancement

#75 Moved gc documentation to documentation folder
  documentation/Handling Garbage Collection.md
Labels: documentation, Organization
